### ISSUE TITLE
failed to install on Windows 8.1

### ISSUE THREAD

**Issue by jpluimers** [eqot/atom-broadcast#10]
Is this a `broadcast` or `Atom` issue?

The below occurs every time I try to install `broadcast`. Other packages install fine.

~~~
Installing “broadcast@0.3.14” failed.Hide output…

> oniguruma@6.1.1 install C:\Users\jeroenp\AppData\Local\Temp\apm-install-dir-116926-4780-144x3q7\node_modules\broadcast\node_modules\oniguruma
> node-gyp rebuild


C:\Users\jeroenp\AppData\Local\Temp\apm-install-dir-116926-4780-144x3q7\node_modules\broadcast\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\jeroenp\AppData\Local\Temp\apm-install-dir-116926-4780-144x3q7
`-- (empty)


(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\request\request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\request\request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\request\request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\request\request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\request\request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\request\request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\request\request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\jeroenp\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Users\\jeroenp\\AppData\\Local\\atom\\app-1.11.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\jeroenp\\AppData\\Local\\atom\\app-1.11.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\jeroenp\AppData\Local\Temp\apm-install-dir-116926-4780-144x3q7\node_modules\broadcast\node_modules\oniguruma
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\jeroenp\AppData\Local\Temp\apm-install-dir-116926-4780-144x3q7\package.json'
npm WARN apm-install-dir-116926-4780-144x3q7 No description
npm WARN apm-install-dir-116926-4780-144x3q7 No repository field.
npm WARN apm-install-dir-116926-4780-144x3q7 No README data
npm WARN apm-install-dir-116926-4780-144x3q7 No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\jeroenp\\AppData\\Local\\atom\\app-1.11.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\jeroenp\\AppData\\Local\\atom\\app-1.11.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\jeroenp\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\jeroenp\\.atom\\.apmrc" "install" "C:\\Users\\jeroenp\\AppData\\Local\\Temp\\d-116926-4780-1hpu72r\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jeroenp\AppData\Local\Temp\apm-install-dir-116926-4780-144x3q7\npm-debug.log
npm ERR! code 1
~~~

**Comment by eqot** [comment]
Are you using Atom (v1.11.2) or Atom Beta (v1.12.0-beta*) ?

I encountered the same issue of oniguruma with Atom Beta on Mac but no issues with Atom.

**Comment by jpluimers** [comment]
I'm at Atom v1.11.2 on Windows x64 8.1 Enterprise. These bits from the log indicate so as well:

```
npm ERR! argv "C:\\Users\\jeroenp\\AppData\\Local\\atom\\app-1.11.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\jeroenp\\AppData\\Local\\atom\\app-1.11.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\jeroenp\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\jeroenp\\.atom\\.apmrc" "install" "C:\\Users\\jeroenp\\AppData\\Local\\Temp\\d-116926-4780-1hpu72r\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
```

What are `oniguruma@6.1.1`  and ` node-gyp`?

How can I check those are not broken?

**Comment by eqot** [comment]
According to the log,

> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

you probably need to install python and/or configure environment variable of PYTHON.

[oniguruma](https://github.com/atom/node-oniguruma) is a regular expressions library which this package depends on, and [node-gyp](https://github.com/nodejs/node-gyp) is a build tool.

Please note that you need Python v2.7 rather than v3.x.x since node-gyp does not support v3.

**Comment by jpluimers** [comment]
Thanks. That likely is the issue. Please document those requirements in the README.md
