### ISSUE TITLE
broadcast of reStructuredText Preview Pandoc: Uncaught TypeError: this.editor.getBuffer is not a function #12

### ISSUE THREAD

**Issue by jpluimers** [eqot/atom-broadcast#13]
Related to https://github.com/eqot/atom-broadcast/issues/12 which now works for Markdown, but not for [reStructuredText Preview Pandoc](https://atom.io/packages/rst-preview-pandoc):

[Enter steps to reproduce:]

1. Open a .rst file
2. In the `Packages` menu, click `reStructuredText Preview Pandoc` then `Toggle Preview`
3. In the preview, right click, then choose `Enable broadcast`

- expected: broadcast http://localhost:8000 to open and update
- actual: error

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [broadcast](https://github.com/eqot/atom-broadcast) package 0.4.0

### Stack Trace

Uncaught TypeError: this.editor.getBuffer is not a function

```
At /Users/jeroenp/.atom/packages/broadcast/lib/broadcast-target.coffee:27

TypeError: this.editor.getBuffer is not a function
    at /packages/broadcast/lib/broadcast-target.coffee:27:9)
    at BroadcastServer.module.exports.BroadcastServer.start (/packages/broadcast/lib/broadcast-server.coffee:23:19)
    at Object.start (/packages/broadcast/lib/broadcast.coffee:35:13)
    at /packages/broadcast/lib/broadcast.coffee:29:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1306:1)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -6:57.8.0 broadcast:start (h2.)
     -6:42.2.0 find-and-replace:show (div.markdown-preview.native-key-bindings)
     -6:39.6.0 find-and-replace:find-next (input.hidden-input)
     -6:38.1.0 find-and-replace:show (input.hidden-input)
     -6:37 find-and-replace:find-next (input.hidden-input)
  4x -6:30.3.0 core:move-left (input.hidden-input)
     -4:40.4.0 rst-preview-pandoc:toggle (input.hidden-input)
     -4:35.8.0 broadcast:start (li.)
     -2:16.6.0 settings-view:open (input.hidden-input)
     -1:05.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:50.1.0 application:open (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  5x -0:38.8.0 core:move-down (input.hidden-input)
     -0:37.7.0 core:move-up (input.hidden-input)
     -0:16.5.0 core:close (input.hidden-input)
     -0:06.1.0 broadcast:start (li.)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-html-preview 0.1.22 
atom-keyboard-macros 0.9.2 
atom-wrap-in-tag 0.6.0 
autocomplete-xml 0.9.4 
broadcast 0.4.0 
busy-signal 1.4.1 
close-tags 0.6.0 
color-picker 2.2.5 
console-panel 0.2.1 
counter 0.3.5 
emmet 2.4.3 
export-html 3.1.0 
file-icons 2.1.7 
git-plus 7.9.2 
intentions 1.1.2 
language-batch 0.4.0 
language-bbcode 0.1.1 
language-innosetup 2.11.4 
language-pascal 0.20.2 
language-plantuml 0.2.0 
language-restructuredtext 1.1.0 
language-routeros-script 0.2.0 
linter 2.1.4 
linter-ui-default 1.6.0 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.5 
nav-panel 0.0.11 
nav-panel-plus 0.3.0 
omnisharp-atom 0.31.2 
pandoc-convert 1.1.0 
plantuml-preview 0.12.9 
print-atom 0.1.1 
rot13 0.3.0 
rst-preview-pandoc 0.1.12 
sort-lines 0.14.0 
sync-settings 0.8.1 
tabs-to-spaces 1.0.3 
tool-bar-markdown-writer 0.2.0 
xml-formatter 0.10.0 
xml-tools 0.2.1 
```

**Comment by NoahCardoza** [comment]
I am also having the problem when I try to use broadcast with [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus).

It works with the builtin markdown-preview-plus but it is just too ugly. I would realy like to get this working as I am teaching a class and this this would be a great way to share examples to the class.

This still seems to be an issue, is there any update? I'd be willing to try and fix it if anyone could point me in the right direction.

**Comment by capogreco** [comment]
this is also an issue when trying to broadcast markdown rendered with [markdown-preview-enhanced](https://atom.io/packages/markdown-preview-enhanced).

the package seems to work nicely with markdown-preview, but in order to be able to render markdown of maths equations to a browser, compatibility would be required with at least one of markdown-preview-plus or markdown-preview-enhanced.
