### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [eqot/atom-broadcast#14]
> oniguruma@6.2.1 install C:\Users\kshar\AppData\Local\Temp\apm-install-dir-117514-6896-1djj31i.12ugs6ecdi\node_modules\broadcast\node_modules\oniguruma
> node-gyp rebuild

C:\Users\kshar\AppData\Local\Temp\apm-install-dir-117514-6896-1djj31i.12ugs6ecdi\node_modules\broadcast\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Development\Software\atom\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Development\Software\atom\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\kshar\AppData\Local\Temp\apm-install-dir-117514-6896-1djj31i.12ugs6ecdi
`-- (empty)

(node:4608) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:4608) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:4608) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:4608) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:4608) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:4608) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:4608) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Development\Software\atom\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Development\Software\atom\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Development\Software\atom\resources\app\apm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Development\\Software\\atom\\resources\\app\\apm\\bin\\node.exe" "C:\\Development\\Software\\atom\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kshar\AppData\Local\Temp\apm-install-dir-117514-6896-1djj31i.12ugs6ecdi\node_modules\broadcast\node_modules\oniguruma
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\kshar\AppData\Local\Temp\apm-install-dir-117514-6896-1djj31i.12ugs6ecdi\package.json'
npm WARN apm-install-dir-117514-6896-1djj31i.12ugs6ecdi No description
npm WARN apm-install-dir-117514-6896-1djj31i.12ugs6ecdi No repository field.
npm WARN apm-install-dir-117514-6896-1djj31i.12ugs6ecdi No README data
npm WARN apm-install-dir-117514-6896-1djj31i.12ugs6ecdi No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Development\\Software\\atom\\resources\\app\\apm\\bin\\node.exe" "C:\\Development\\Software\\atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\kshar\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\kshar\\.atom\\.apmrc" "install" "C:\\Users\\kshar\\AppData\\Local\\Temp\\d-117514-6896-1t471x1.f8lvijxlxr\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kshar\AppData\Local\Temp\apm-install-dir-117514-6896-1djj31i.12ugs6ecdi\npm-debug.log
npm ERR! code 1

**Comment by lumenwrites** [comment]
Hi there! Did you figure out the solution?
