### ISSUE TITLE
Cannot install broadcast

### ISSUE THREAD

**Issue by sveinburne** [eqot/atom-broadcast#6]
Hi! Your package sounds awesome but I cannot install it in my ubuntu 14.04 distribution. Any help would be greatly appreciated :)

``` bash
$ apm install broadcast
Installing broadcast to /home/svein/.atom/packages ✗

> oniguruma@5.1.2 install /tmp/apm-install-dir-116129-7205-13uuf1u/node_modules/broadcast/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
> node-gyp rebuild


Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-116129-7205-13uuf1u/node_modules/broadcast/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/svein/.atom/.apm/.apmrc" "--userconfig" "/home/svein/.atom/.apmrc" "install" "/tmp/d-116129-7205-qkv3fj/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@5.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@5.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116129-7205-13uuf1u/npm-debug.log
```
Then I wanted to output the .log but...

``` bash
$ cat /tmp/apm-install-dir-116129-7205-13uuf1u/npm-debug.log
cat: /tmp/apm-install-dir-116129-7205-13uuf1u/npm-debug.log: No such file or directory
```

``` bash
$ atom --version
1.0.5
```

Are my node and / or npm packages outdated?

**Comment by eqot** [comment]
Thank you very much for filing the issue.
I tried to reproduce the issue with Atom 1.5.4 on Ubuntu 14.04 but installation of this package was successfully finished without errors.
Could you try installation again with the latest Atom, please?

**Comment by sveinburne** [comment]
Hi and thanks for your fast reply :+1: . Indeed my atom client was pretty outdated (1.0.5) and broadcast now works as espected :) Have a good day !

**Comment by eqot** [comment]
Glad to hear that. Thanks!
